version: 2
updates:
  # Maintain dependencies for Python packages in pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
